### ISSUE TITLE
Add configuration variables

### ISSUE THREAD

**Issue by coastalwhite** [coastalwhite/lemurs#71]
Add variables which can be inserted onto other configuration options

This would look like:
```toml
variables = {
    focus-color = "#FF0000",
}

# ... snip

switcher_color = "${focus-color}"
```
